spring:
  application:
    name: firstcome

  datasource:
    url: jdbc:mysql://localhost:3306/leaderboard?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mpro
    password: mpro1234
    hikari:
      maximum-pool-size: 30
      max-lifetime: 30000
      connection-timeout: 3000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  data:
    redis:
      url: redis://localhost:6379
      client-type: lettuce
      lettuce:
        pool:
          max-active: 30
          max-idle: 8
          min-idle: 1
          max-wait: 1000ms

server:
  port: 8000